services:
  nicotine:
    platform: linux/amd64
    build: .
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 6080:6080
      - 2234:2234
    volumes:
      - config:/data/.config/nicotine
      - data:/data/.local/share/nicotine
      - downloads:/data/downloads
volumes:
  config:
  data:
  downloads:
